version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html/:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - kirby
