version: "3"
services:
  httpd:
    build:
      context: "./docker/httpd/"
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/:ro
    networks:
      - kirby
